# Generated by Django 3.2.8 on 2021-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("descrition", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        )
    ]
