# Generated by Django 3.2.8 on 2022-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=18)),
                ("value", models.CharField(max_length=18)),
            ],
        )
    ]
