# Generated by Django 3.2.8 on 2022-02-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="email",
            field=models.CharField(default="", max_length=50),
        )
    ]
