# Generated by Django 3.2.8 on 2022-02-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0002_cartitem_email")]

    operations = [
        migrations.AlterField(
            model_name="cartitem", name="email", field=models.CharField(max_length=50)
        )
    ]
