# Generated by Django 3.2.8 on 2022-02-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("product", "0002_specification")]

    operations = [migrations.RemoveField(model_name="specification", name="value")]
