# Generated by Django 3.2.8 on 2022-02-07 16:39

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [("product", "0003_remove_specification_value")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="items",
            field=django_jsonform.models.fields.JSONField(default=""),
        )
    ]
