# Generated by Django 3.2.8 on 2022-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0003_alter_cartitem_email")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="city",
            field=models.CharField(
                choices=[("WRO", "Wrocław"), ("RzE", "Rzeszów"), ("GDA", "Gdańsk")],
                default="WRO",
                max_length=3,
            ),
        ),
        migrations.DeleteModel(name="City"),
    ]
