# Generated by Django 3.2.8 on 2021-10-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Product", "0004_auto_20211008_1227")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
