# Generated by Django 3.2.8 on 2022-02-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220212_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(choices=[('WRO', 'Wrocław'), ('RZE', 'Rzeszów'), ('GDA', 'Gdańsk')], default='WRO', max_length=3),
        ),
    ]
