# Generated by Django 3.2.8 on 2022-02-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("product", "0004_product_items")]

    operations = [migrations.RemoveField(model_name="product", name="items")]
