# Generated by Django 3.2.8 on 2022-02-07 17:59

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [("product", "0006_alter_specification_name")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to=product.models.path_and_rename),
        )
    ]
