# Generated by Django 3.2.8 on 2021-10-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Product", "0006_alter_product_image")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        )
    ]
