# Generated by Django 3.2.8 on 2021-10-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_computer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='Ram',
            new_name='ram',
        ),
    ]
