# Generated by Django 3.2.8 on 2021-10-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Product", "0010_auto_20211010_2024")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(null=True, upload_to="images/categories/"),
        )
    ]
