# Generated by Django 3.2.8 on 2021-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Product", "0011_category_image")]

    operations = [
        migrations.AddField(
            model_name="city",
            name="shortcut",
            field=models.CharField(max_length=3, null=True),
        )
    ]
