# Generated by Django 3.2.8 on 2022-05-19 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0012_alter_cartitem_released_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("image", models.TextField(max_length=100)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("WRO", "Wrocław"),
                            ("RZE", "Rzeszów"),
                            ("GDA", "Gdańsk"),
                        ],
                        default="WRO",
                        max_length=3,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("spec", django_jsonform.models.fields.JSONField(null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="product.category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product",
                "verbose_name_plural": "historical products",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCartItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("order_id", models.PositiveIntegerField(default=0)),
                ("employee_name", models.CharField(max_length=50)),
                ("login", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=50)),
                ("nip", models.CharField(blank=True, max_length=10)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("order_date", models.DateField(blank=True, editable=False)),
                ("bill", models.BooleanField(default=False)),
                ("released", models.BooleanField(default=False)),
                ("released_date", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cart item",
                "verbose_name_plural": "historical cart items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
