# Generated by Django 3.2.8 on 2021-12-16 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Product", "0015_rename_carts_cart"),
    ]

    operations = [migrations.RenameModel(old_name="Cart", new_name="CartItem")]
