# Generated by Django 3.2.8 on 2022-05-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0020_auto_20220524_0004")]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcartitem",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
