# Generated by Django 3.2.8 on 2023-02-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20220628_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='login',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcartitem',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcartitem',
            name='login',
            field=models.CharField(max_length=30),
        ),
    ]
